package com.itau.todo.domain.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@DynamoDBTable(tableName = "quadros")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Quadro {

    public Quadro(String tipo, String name) {
        this.tipo = tipo;
        this.name = name;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBRangeKey
    private String tipo;
    private String name;
}
